### ISSUE TITLE
Event TODO

### ISSUE THREAD

**Issue by sinteary** [cs3216-2021-a3-group12/slotify-backend#6]
**Events**
YL working on tasks below
- [x] Create event (only for group admins)
     - [x] Create event
     - [x] Create event slots (need to confirm shape)
- [x] Update
- [x] Delete event (only for group admins)
- [x] View single event
- [x] List events (filter by isPublic, groupId)
- [x] Add image for event
---
Cynthia working on tasks below
- [x] List user's signed-up events

**Sign ups**
- [x] Create user sign up for an event
- [x] Delete user sign up for an event (and move up waitlisted people if any)
     - [ ] Notify waitlisted people that they are now confirmed
- [x] View user sign ups (only for group admins)
- [x] Mark attendance for signups (group admins)
- [x] View event slots and their statuses
- [x] View individual slot (for refreshing purposes when numbers are updated)
- [ ] Update slot (change limit of each slot) -- (todo only after frontend layout for this is confirmed)
