### ISSUE TITLE
Auth TODO

### ISSUE THREAD

**Issue by sinteary** [cs3216-2021-a3-group12/slotify-backend#8]
- [x] Add details for user (NUS net id, matric no. etc) + relevant API to update them after user is successfully registered
- [x] Token refresh
- [ ] Determine a way for user to update email (and resend verification)

**Ranked stretch goals**
- [ ] Integration with socials
- [ ] Reset password by email
